### ISSUE TITLE
How to setup this gem to use with RSpec?

### ISSUE THREAD

**Issue by bruno-berchielli** [hoppergee/multi-tenant-support#11]
Hello, how is the best setup to use this gem alongside Rspec? 

For reference this is act_as_tenant setup guide for RSpec https://github.com/ErwinM/acts_as_tenant#testing

Thanks

**Comment by hoppergee** [comment]
Hi, @bruno-berchielli 

I'm not much like the acts_as_tenant's way of setup RSpec. It's not very friendly to newcomers and patch some code for test only.

I'm working on the setup process under minitest now, and found a well solution. Will head to RSpec after that in the next few days.
