### ISSUE TITLE
A way to allow updates across multiple tenants, as SuperAdmin

### ISSUE THREAD

**Issue by camiloforero** [hoppergee/multi-tenant-support#14]
Hey. I've been using your gem for a while, it looks more polished than all the others. But I'm facing an issue.

There are times when, as a super admin, I need to execute certain maintenance operations over all tenants/tenanted records.
For example, fixing the counters of the `counter_culture` gem, or applying an application wide value update inside a migration.

But although this gem allows reading across tenants, it doesn't allow updating across them.

I understand maybe you do this as an additional security feature but, sometimes doing this *is* necessary; batching operations per tenant would get too boilerplaty and too database inefficient to justify the extra security gained from restricting update operations to a single tenant.

So do you have plans for supporting this soon? Is there something stopping you?

**Comment by hoppergee** [comment]
Hi, @camiloforero 
I'm glad to hear that you like this gem.

I think it is a reasonable requirement. I will try to implement it in the next minor version.

**Comment by hoppergee** [comment]
@camiloforero 
I just released a new version to support operation across tenant with:

```ruby
MultiTenantSupport.turn_off_protection do
  # ...
end
```

I also update the README, you can find more details there.
