### ISSUE TITLE
When query multiple model data on same page it start creating issues 

### ISSUE THREAD

**Issue by snawar92** [hoppergee/multi-tenant-support#17]
When querying multiple model data on the same page it starts creating issues on each where query 

on single model works fine but on multiple model queries on same method creates issues 

eg 
def dashboard
@question = current_user.questions
@answers = Answer.where(user_id: current_user.id)
end

both question and answer has 
  belongs_to_tenant :user
  belongs_to :user

Errors:
missing attribute :user_id
MultiTenantSupport::MissingTenantError

**Comment by snawar92** [comment]
@hoppergee  take a look at this issue

**Comment by hoppergee** [comment]
I try your above code in a demo, it works fine.
Can you offer more detail? like controller, schema and what're you trying to do?

**Comment by snawar92** [comment]
> 

in the existing big sass app it is creating an issue, let me create a similar issue in the public Github app then I will ping you, give me 1-2 days @hoppergee
