### ISSUE TITLE
how to allow allow_read_across_tenant in seed file

### ISSUE THREAD

**Issue by snawar92** [hoppergee/multi-tenant-support#18]
how to allow MultiTenantSupport.allow_read_across_tenant in seed file ,  tried adding this line in seed file but didn't worked

**Comment by snawar92** [comment]
@hoppergee

**Comment by hoppergee** [comment]
What kinds of "didn't work"? Any error messages? It will be better if you can give an example or sample code.

**Comment by snawar92** [comment]
@hoppergee after wrapping seed file code in do blocked worked for me 

MultiTenantSupport.without_current_tenant do
  MultiTenantSupport.allow_read_across_tenant
  MultiTenantSupport.turn_off_protection

==========seed file data  ===========

end

it would be great if you add console like feature in initializer 

eg:
  seed do |config|
    config.allow_read_across_tenant_by_default = true
  end

**Comment by hoppergee** [comment]
> it would be great if you add console like feature in initializer

Maybe you can try to get this feature by simply put `MultiTenantSupport.allow_read_across_tenant` on the top. Then it behaves like "default"

**Comment by snawar92** [comment]
> > it would be great if you add console like feature in initializer
> 
> Maybe you can try to get this feature by simply put `MultiTenantSupport.allow_read_across_tenant` on the top. Then it behaves like "default"

it didn't worked  throwing error 
    MultiTenantSupport::MissingTenantError: MultiTenantSupport::MissingTenantError

**Comment by hoppergee** [comment]
The current_tenant is nil by default. When you need to create records under a tenant you can use 

```ruby
MultiTenantSupport.under_tenant(your_tenant) do
  # ...
end
```

BTW, most time you don't need `MultiTenantSupport.without_current_tenant`, unless you are doing something like this:

```ruby
MultiTenantSupport.under_tenant(your_tenant) do
  # ...
  MultiTenantSupport.without_current_tenant do
    # ...
  end
end
```

**Comment by snawar92** [comment]
@hoppergee helpful , you can close this issue, you did great work @hoppergee 🔥
